/** Ambient type of the virtual module generated by dsh-component-stories. */
declare module 'virtual:component-stories' {
  /** One story's live-preview registration, keyed by its library record id. */
  export function has(id: string): boolean
  /** Every registered story's record id. */
  export function ids(): string[]
  /** Mount one story's live preview into the container; returns its disposer. */
  export function mount(id: string, container: HTMLElement): Promise<void | (() => void)>
}
